version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(deps): '
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(deps): '
  - package-ecosystem: npm
    directory: /demo
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(deps): demo'
