name: Run Unit Tests

# only run on pushes to the main branch when the lib folder changes
on:
  push:
    branches:
      - dev
    paths:
      - 'lib/**'

  pull_request:
    branches:
      - dev
    paths:
      - 'lib/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
